### ISSUE TITLE
Why the HMR doesn't work?

### ISSUE THREAD

**Issue by Verten** [rafaelhz/react-material-admin-template#1]
Why the HMR doesn't work?

**Comment by rafaelhz** [comment]
It should work. There's some error logging?

**Comment by Verten** [comment]
@rafaelhz ,sorry, and this is my fault, i was putting the project into some path like 'xxx\xx(xx)', so the HMR doesn't work.

**Comment by pmirandaarias** [comment]
Is not working in my case. I'm testin the app in Cloud9, I've run other apps with HMR without problems, but now I'm getting in the console manye of:

__webpack_hmr	(canceled)	eventsource	Other	0 B	18.99 s
__webpack_hmr	(canceled)	eventsource	Other	0 B	20.00 s
__webpack_hmr	(canceled)	eventsource	Other	0 B	20.00 s
__webpack_hmr	(canceled)	eventsource	Other	0 B	19.01 s
__webpack_hmr	(canceled)	eventsource	Other	0 B	20.00 s
__webpack_hmr	(canceled)	eventsource	Other	0 B	20.00 s
__webpack_hmr	(canceled)	eventsource	Other	0 B	20.00 s
__webpack_hmr	(canceled)	eventsource	Other	0 B	19.00 s
__webpack_hmr	(canceled)	eventsource	Other	0 B	19.00 s


edit: my mistake. In Cloud9 I have to use https, I was testins with http. With https I don't have the mentioned problem. Now... why?
