### ISSUE TITLE
Dúvida com material

### ISSUE THREAD

**Issue by gabrielferreiraa** [rafaelhz/react-material-admin-template#4]
Opa, tudo certo @rafaelhz ? Cara, só uma pergunta, estou começando a estudar React para criar algumas aplicações no meu trabalho. 

Vejo em seu problema que você utilizou Material-UI. Por que? 
Hoje que comecei a pesquisar sobre esses "temas em React" para criar um admin bem legal. Vi também que tem o [React Tollbox](http://react-toolbox.com), você sabe qual é a diferente entre esses 2?

Essa estrutura em que você utilizou , consigo usa-la em aplicações complexas e grandes ou é apenas exemplos e etc?

Uma outra pergunta em que não encontrei respostas, esses Design Materials que citei e que você utilizou, por exemplo o Date Picker, há como setar localização etc? 

Obrigado, e parabéns pelo trabalha com o React.

**Comment by rafaelhz** [comment]
E ae Gabriel blz?

Existem varias opcoes de suite de componentes pra React, como o React ToolBox que eh mto bom tbm. 

O material-ui na minha opiniao eh o mais completo, e atendeu os requisitos do projeto que utilizei. Alem disso ele tem 22 mil estrelas no git, com quase 500 contribuitors, estao sempre incluindo novos components e corrigindo bugs, compatilidade entre browsers e etc, a comunidade por tras eh mto forte.

Estou utilizando em um projeto grande, a estrutura eh bem parecida com desse demo, mas estou utilizando com Redux tambem pra controlar o estado da aplicacao.

Sobre o datepicker voce consegue setar o locale nele sim, pra ficar em portugues, no propria documentacao explica como fazer.

Espero ter ajudado. Ate mais!
